default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: book_api_marvio_development

test:
  <<: *default
  database: book_api_marvio_test

production:
  <<: *default
  database: book_api_marvio_production
  username: book_api_marvio
  password: <%= ENV['BOOK_API_MARVIO_DATABASE_PASSWORD'] %>
